# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    sudo python -m pip uninstall pip && sudo apt install python-pip --reinstall
    pip install pytest pytest-azurepipelines pytest-cov wheel setuptools injector
    pip install -r ./backend/requirements.txt
  displayName: 'Install dependencies'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'config.py'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '**'
    TargetFolder: 'backend'

- script: |
    find -type d -name 'backend'
    cd ./backend
    python -m pytest --cov=backend_tests ./backend_tests --cov-report html
  displayName: 'pytest'